services:
  - type: web
    name: ai-lesson-creator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/healthz
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production